### DISCUSSION TITLE
Any idea why the url is blank for curseforge mods in the .index/mod.toml?

### DISCUSSION THREAD

**Discussion by EchoEllet** [PrismLauncher/PrismLauncher#2394] [Q&A] [answered]
When I try to download any mod using the launcher, it will create some metadata that has the same underline data as some other launchers, when installing any mod from CurseForge, it will always have blank URL field:

```toml

filename = 'moredragoneggs-4.0.jar'
name = 'More Dragon Eggs'
side = 'both'

[download]
hash = '22122de407d0df09a0f36c580ed56c22faa52551'
hash-format = 'sha1'
mode = 'metadata:curseforge'
url = ''

[update.curseforge]
file-id = 4670879
project-id = 358700

```

When downloading and installing mods from Modrinth mod provider it will have a valid download URL:

```toml

filename = 'architectury-9.2.14-forge.jar'
name = 'Architectury API'
side = 'both'

[download]
hash = 'cf67f2050cafa00f0bee42e6d7bef77fdb808ac4f71742f7b4d6d5c1e6ffb49561a5a252f332d2b78a9767bdb5faa284611790dba303fbdc736ae36d794f61c7'
hash-format = 'sha512'
mode = 'url'
url = 'https://cdn.modrinth.com/data/lhGA9TYQ/versions/1MKTLiiG/architectury-9.2.14-forge.jar'

[update.modrinth]
mod-id = 'lhGA9TYQ'
version = '1MKTLiiG'

```

The reason I'm interested in this field because I'm creating a script for syncing the Minecraft content instance to all players from one player and I decided to use the MultiMc mods metadata and migrate all the data to the script in a single command, I would like to know more about when the URL is blank so I handle this correctly

Thank you.
