### ISSUE TITLE
Rename "Delete metadata" to convey its goal

### ISSUE THREAD

**Issue by Madis0** [PrismLauncher/PrismLauncher#1814]
### Role

I play modded Minecraft

### Suggestion

I suggest changing "delete metadata" to "reset download location"

### Benefit

Because it sounds less destructive and more obvious

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In https://github.com/PrismLauncher/PrismLauncher/issues/1528, a "delete metadata" button was added. I wondered what it does until I read that issue.

As the issue explains, it only changes the _download location that Prism uses to update it_. It does not nullify mod's manifest, remove version restrictions or something like that. It doesn't even gray out after clicked.

Hence, I suggest making the name more obvious to the users. "Reset download location" may be a bit long, so I'm open to alternative names that would still better convey the idea.

**Comment by Scrumplex** [comment]
The metadata file this deletes looks about like this:

```toml
name = "No Chat Reports"
filename = "NoChatReports-FABRIC-1.20.1-v2.2.2.jar"
side = "both"

[download]
mode = "url"
url = "https://cdn.modrinth.com/data/qQyHxfxd/versions/HeZZR2kF/NoChatReports-FABRIC-1.20.1-v2.2.2.jar"
hash-format = "sha512"
hash = "3213e37fc12205e49f69a6c295c8c3237d8464d63dedbfbac4901892752741d22ebf7e1b40d6683143e70ca158fc95b00c2af177a1263038edce9a46b6cbeb79"

[update]
[update.modrinth]
mod-id = "qQyHxfxd"
version = "HeZZR2kF"
```

Maybe we could rename it to `Reset update metadata` but that makes the button very wide
